package core

const (
	AUTH_UNKNOWN_KEY             = "AUTH_UNKNOWN_KEY"
	AUTH_ACCOUNT_DISABLED        = "AUTH_ACCOUNT_DISABLED"
	AUTH_CREDENTIAL_MISSING      = "AUTH_CREDENTIAL_MISSING"
	AUTH_CREDENTIAL_UNAUTHORIZED = "AUTH_CREDENTIAL_UNAUTHORIZED"
	AUTH_CREDENTIAL_FORBIDDEN    = "AUTH_CREDENTIAL_FORBIDDEN"
	AUTH_WRONG_CODER_IDENTITY    = "AUTH_WRONG_CODER_IDENTITY"
	AUTH_CODER_UNAVAILABLE       = "AUTH_CODER_UNAVAILABLE"
	AUTH_CODER_INCOMPATIBLE      = "AUTH_CODER_INCOMPATIBLE"

	ROUTE_INVALID_PAYLOAD = "ROUTE_INVALID_PAYLOAD"
	ROUTE_SUFFIX_DENIED   = "ROUTE_SUFFIX_DENIED"
	ROUTE_PORT_DENIED     = "ROUTE_PORT_DENIED"
	ROUTE_NAME_INVALID    = "ROUTE_NAME_INVALID"

	TUNNEL_LIMIT_REACHED        = "TUNNEL_LIMIT_REACHED"
	TUNNEL_PROCESS_START_FAILED = "TUNNEL_PROCESS_START_FAILED"
	TUNNEL_START_TIMEOUT        = "TUNNEL_START_TIMEOUT"
	TUNNEL_CODER_EXITED         = "TUNNEL_CODER_EXITED"
	TUNNEL_STREAM_FAILED        = "TUNNEL_STREAM_FAILED"
	TUNNEL_CANCELLED            = "TUNNEL_CANCELLED"

	STORE_UNAVAILABLE         = "STORE_UNAVAILABLE"
	STORE_GENERATION_CONFLICT = "STORE_GENERATION_CONFLICT"

	CRYPTO_KEY_UNAVAILABLE = "CRYPTO_KEY_UNAVAILABLE"
	CRYPTO_DECRYPT_FAILED  = "CRYPTO_DECRYPT_FAILED"
)
